version: '3.1'
services:
  mediawiki:
    build: ./mediawiki
    image: mediawiki
    container_name: mediawiki
    links:
        - mariadb
    volumes:
        - backup-volume:/backup
        - mediawiki-volume:/opt/mediawiki
        - images-volume:/opt/mediawiki/images
    ports: 
        - 9000:9000
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    links:
      - mediawiki
    volumes:
        - mediawiki-volume:/opt/mediawiki
        - images-volume:/opt/mediawiki/images
        - /root/.acme.sh/${HOSTNAME}/${HOSTNAME}.cer:/opt/ssl/server.cer:ro
        - /root/.acme.sh/${HOSTNAME}/${HOSTNAME}.key:/opt/ssl/server.key:ro
    ports:
      - 80:80
      - 443:443
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - database-volume:/var/lib/mysql
      - backup-volume:/restore/
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGETHIS
    ports:
      - 3306:3306
  elasticsearch_01:
    build: ./elastic_search
    image: elasticsearch:5
    container_name: elasticsearch_01
    volumes:
      - elastic-volume-01:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  mediawiki-volume:
  images-volume:
  backup-volume:
  database-volume:
  elastic-volume-01: